set(CMAKE_SYSTEM_NAME Linux)
set(TOOLCHAIN_PATH /opt/toolchain/t113-i/arm-buildroot-linux-gnueabihf_sdk-buildroot/bin/)
set(CMAKE_C_COMPILER ${TOOLCHAIN_PATH}/arm-buildroot-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PATH}/arm-buildroot-linux-gnueabihf-g++)
set(CMAKE_SYSROOT /opt/toolchain/t113-i/arm-buildroot-linux-gnueabihf_sdk-buildroot/arm-buildroot-linux-gnueabihf/sysroot)
